### ISSUE TITLE
Thirdperson is not working

### ISSUE THREAD

**Issue by wsignin** [CredixYt/Credixware#1]
I cant enable third person. Can u help me?

**Comment by CredixYt** [comment]
EDIT: Also make sure that in `Headers/Interfaces.h` you have `g_pInput = *(CInput**)((*(DWORD**)g_pClient)[16] + 0x1);` uncommented (because this line has caused multiple crashes it will be uncommented, until I find a solution)

Make sure that in your `OverrideView.h` you have the following code before calling `oOverrideView`:
https://pastebin.com/uMe4jBcR

`bThirdperson` and `ThirdpersonOffKey` (the key you need to hold down to temporarily disable ThirdPerson) can be found in the namespace Settings in `Hacks/Hacks.h` or you can simply replace them with `true` and any VirtualKey. Hope this helps!

If your problem persists, feel free to add me on Discord: `Credix#0001`

**Comment by CredixYt** [comment]
A week has passed without any reply. Assuming solved
